version: '3.3'
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: skt_db_image
    environment:
      MYSQL_DATABASE: 'skt_activity'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "4000:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "./my-db:/var/lib/mysql"
      - "./procedures.sql:/docker-entrypoint-initdb.d/init.sql"
# Names our volume
volumes:
  my-db: